server:
  port: ${PORT}

spring:
  security:
    user:
      name: scifunapp
      password: password123

  data:
    mongodb:
      uri: ${MONGODB_URI}

# ==== JWT ANA MAIL====
app:
  jwt:
    secret: ${JWT_SECRET}
    expiresSeconds: ${JWT_EXPIRES_SECONDS}

  sendgrid:
    apiKey: ${SENDGRID_API_KEY}

  mail:
    from: ${MAIL_FROM}


logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.messaging.simp.stomp: DEBUG

# ==== Cloudinary ====
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

# ==== Elastic ====
es:
  node: ${ES_NODE}
  apiKey: ${ES_API_KEY}

# ==== ZaloPay Sandbox ====
zalopay:
  app-id: ${ZP_APP_ID}
  key1: ${ZP_KEY1}
  create-endpoint: ${ZP_CREATE_ENDPOINT}
  query-endpoint: ${ZP_QUERY_ENDPOINT}

# ==== Client ====
scifun:
  client-url: ${CLIENT_URL}
